spring.application.name=limits-service
spring.config.import=optional:configserver:http://localhost:8888

#Below are some additional properties that can be used for different profiles (e.g., qa,dev,prod):
#how to use them: uncomment the relevant lines and set the active profile accordingly and call localhost:8080/limits
spring.profiles.active=qa
spring.cloud.config.profile=qa

#spring.profiles.active=prod
#spring.cloud.config.profile=prod

#limits-service.minimum=3
#limits-service.maximum=997