spring.application.name=naming-server
server.port=8761
#We Dont want to register our naming server with itself, so we set the following 2 properties:
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
